version: "3.9"
services:

  configsvr0:
    image: mongo
    command: mongod --configsvr --replSet configsvr --port 27017 --dbpath /data/db --keyFile /data/keyfile
    volumes:
      - configsvr0:/data/db
      - ./keyfile:/data/keyfile:ro
  configsvr1:
    image: mongo
    command: mongod --configsvr --replSet configsvr --port 27017 --dbpath /data/db --keyFile /data/keyfile
    volumes:
      - configsvr1:/data/db
      - ./keyfile:/data/keyfile:ro
  configsvr2:
    image: mongo
    command: mongod --configsvr --replSet configsvr --port 27017 --dbpath /data/db --keyFile /data/keyfile
    volumes:
      - configsvr2:/data/db
      - ./keyfile:/data/keyfile:ro

  shard0svr0:
    image: mongo
    command: mongod --shardsvr --replSet shard0 --port 27017 --dbpath /data/db --keyFile /data/keyfile
    volumes:
      - shard0svr0:/data/db
      - ./keyfile:/data/keyfile:ro
  shard0svr1:
    image: mongo
    command: mongod --shardsvr --replSet shard0 --port 27017 --dbpath /data/db --keyFile /data/keyfile
    volumes:
      - shard0svr1:/data/db
      - ./keyfile:/data/keyfile:ro
  shard0svr2:
    image: mongo
    command: mongod --shardsvr --replSet shard0 --port 27017 --dbpath /data/db --keyFile /data/keyfile
    volumes:
      - shard0svr2:/data/db
      - ./keyfile:/data/keyfile:ro

  shard1svr0:
    image: mongo
    command: mongod --shardsvr --replSet shard1 --port 27017 --dbpath /data/db --keyFile /data/keyfile
    volumes:
      - shard1svr0:/data/db
      - ./keyfile:/data/keyfile:ro
  shard1svr1:
    image: mongo
    command: mongod --shardsvr --replSet shard1 --port 27017 --dbpath /data/db --keyFile /data/keyfile
    volumes:
      - shard1svr1:/data/db
      - ./keyfile:/data/keyfile:ro
  shard1svr2:
    image: mongo
    command: mongod --shardsvr --replSet shard1 --port 27017 --dbpath /data/db --keyFile /data/keyfile
    volumes:
      - shard1svr2:/data/db
      - ./keyfile:/data/keyfile:ro

  mongos0:
    image: mongo
    command: mongos --configdb configsvr/configsvr0:27017,configsvr1:27017,configsvr2:27017 --bind_ip 0.0.0.0 --port 27017 --keyFile /data/keyfile
    volumes:
      - ./keyfile:/data/keyfile:ro
    depends_on:
      - configsvr0
      - configsvr1
      - configsvr2
      - shard0svr0
      - shard0svr1
      - shard0svr2
      - shard1svr0
      - shard1svr1
      - shard1svr2

  mongos1:
    image: mongo
    command: mongos --configdb configsvr/configsvr0:27017,configsvr1:27017,configsvr2:27017 --bind_ip 0.0.0.0 --port 27017 --keyFile /data/keyfile
    volumes:
      - ./keyfile:/data/keyfile:ro
    depends_on:
      - configsvr0
      - configsvr1
      - configsvr2
      - shard0svr0
      - shard0svr1
      - shard0svr2
      - shard1svr0
      - shard1svr1
      - shard1svr2

  haproxy0:
    image: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:27017:27017"
    depends_on:
      - mongos0
      - mongos1

volumes:
  configsvr0:
  configsvr1:
  configsvr2:

  shard0svr0:
  shard0svr1:
  shard0svr2:

  shard1svr0:
  shard1svr1:
  shard1svr2:
